name: Cloudflare Pages Deployment Test

on:
  push:
    branches: [main]

jobs:
  deploy-to-cloudflare-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/actions-pages@v1
        with:
          primary_domain: fabulouslily.com
          build_directory: build